name: Build and Release ToolX

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # THIS IS THE NEW STEP THAT FIXES THE ERROR
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore ToolX.sln

      - name: Build MSIX Packages
        run: |
          msbuild ToolX.sln /p:Configuration=Release /p:Platform=x86 /p:AppxPackageSigningEnabled=false /p:GenerateAppxPackageOnBuild=true
          msbuild ToolX.sln /p:Configuration=Release /p:Platform=x64 /p:AppxPackageSigningEnabled=false /p:GenerateAppxPackageOnBuild=true
          msbuild ToolX.sln /p:Configuration=Release /p:Platform=ARM64 /p:AppxPackageSigningEnabled=false /p:GenerateAppxPackageOnBuild=true
        
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          files: '**/bin/**/*.msix'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
